apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: dlf
namespace: dlf
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - crd.yaml
  - csidriver.yaml
  - daemonset.yaml
  - deployment.yaml
  - dlf.yaml
  - job.yaml
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml
  - storageclass.yaml
configMapGenerator:
- name: dlf-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: kubelet-path
  objref:
    kind: ConfigMap
    name: dlf-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.kubelet-path
configurations:
  - params.yaml